name: "[DEPRECATED] Publish on Docker Hub"

# This workflow is deprecated in favor of the release-triggered workflow
# It will be removed once the new release process is established
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/publish.yml'  # Only trigger if this file is modified

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get package version
        id: version
        run: echo "::set-output name=version::$(awk -F= '/^version/ { print $2 }' pyproject.toml | tr -d ' ' | tr -d '"')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: igormcsouza/gpt4shell:${{ steps.version.outputs.version }}